apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wvdvjd9mu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wvdvjd9mu-nodejs 
  name: wvdvjd9mu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wvdvjd9mu-nodejs 
